name: CI

on: [push, repository_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - uses: hostinger/actions/login@master
      with:
        creds: ${{ secrets.HOSTINGER_CREDENTIALS }}    
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        composer install
    - name: Deploy to Hostinger
      run: hostinger --help
